version: "3.9"
services:
  alpine-build-machine:
    image: arthurnap24/alpine-build-machine:latest
    volumes:
      - ${APP_FOLDER:?Set a valid directory}:/usr/src/myapp
  ubuntu-build-machine:
    image: arthurnap24/ubuntu-build-machine:latest
    volumes:
      - ${APP_FOLDER:?Set a valid directory}:/usr/src/myapp